[package]
name = "getfavicon"
version = "0.1.0"
authors = ["Andrey Kutejko <andy128k@gmail.com>"]

[[bin]]
name = "getfavicon"
path = "src/bin/getfavicon.rs"
doc = false

[dependencies]
regex = "0.2.2"
url = "1.5.1"
reqwest = "0.8.1"
tempfile = "2.1.6"
lazy_static = "1.0.0"
error-chain = "0.11.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"
base64 = "0.8.0"
