[package]
name = "getfavicon"
version = "0.2.0"
authors = ["Andrey Kutejko <andy128k@gmail.com>"]
edition = "2018"

[[bin]]
name = "getfavicon"
path = "src/bin/getfavicon.rs"
doc = false

[dependencies]
regex = "1.0.0"
url = "1.5.1"
reqwest = "0.9.0"
mime = "0.3"
tempfile = "3.0.0"
lazy_static = "1.0.0"
failure = "0.1.1"
structopt = "0.2.4"
base64 = "0.10.0"
